version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_device_db
    restart: always
    environment:
      POSTGRES_USER: device_user
      POSTGRES_PASSWORD: device_pass
      POSTGRES_DB: device_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
